name: gymgate_backend
services:
  gg_api:
    build: .
    container_name: gymgate_api
    restart: on-failure
    command: sh -c "npm run prisma:deploy && npm run build && npm run start"
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${API_PORT}
    volumes:
      - .:/app
      - /app/node_modules
